### ISSUE TITLE
LICENSE file missing

### ISSUE THREAD

**Issue by crshrprt** [LeNomDesFleurs/PHILODENDRON_JUCE#1]
Thank you for this interesting plugin.

I can't find if the source is released under a license. Is there a license?

**Comment by LeNomDesFleurs** [comment]
Hi !

Thanks for the heads up, I added GPL v3 for Hellebore and Philodendron.

Would you mind me asking if you have a particular reason to ask so ?

**Comment by crshrprt** [comment]
Just to know if it's libre software or not. Thank you very much.
